name: Node.js Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm install
<<<<<<< HEAD
    - name: My name is
      run: echo "My name is crashone
=======
    - name: install chromium and other
      run: npx playwright install
>>>>>>> bf7fedaf3933bd98821f74bd998eed8aacdfc5cd
    - name: Run unit tests
      run: npm run test:unit
    - name: Run UI tests
      run: npm run test:ui
